version: "3.8"

services:
  app:
    build: .
    container_name: shortener_app
    restart: always
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "npm run db:migrate && npm run start:dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:16
    container_name: shortener_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
